### ISSUE TITLE
上传文件时报错：okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by MatadorC** [zicheng2019/cxhttp#1]
CxHttp.post("url")
{
       setBody(File(fileName))
}.launch {response->
                
}
以上是上传文件的代码，
在上传文件的时候提示这个“okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR”，
需要在哪里配置？

**Comment by zhzc0x** [comment]
okhttp3的相关配置都可以通过Okhttp3Call来配置，代码如下：
val okhttp3Call = Okhttp3Call{
        callTimeout(15, TimeUnit.SECONDS)
        addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
        protocols(listOf(Protocol.HTTP_1_1))
    }
CxHttpHelper.init(..., call=okhttp3Call)

PS：okhttp3（4.11.0）已经解决这个问题了

**Comment by zhzc0x** [comment]
PS：最新版本的okhttp3（4.11.0）貌似已经解决这个问题了
